---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mulder.fullname" . }}
  labels:
    helm.sh/chart: {{ include "mulder.chart" . }}
    app.kubernetes.io/name: {{ include "mulder.name" . }}
    app.kubernetes.io/version: {{ .Values.image.tag }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- with .Values.deployment.labels }}
{{ tpl (toYaml .) $ | trim | indent 4 }}
    {{- end }}
  {{- with .Values.deployment.annotations }}
  annotations:
{{ tpl (toYaml .) $ | trim | indent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mulder.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mulder.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        {{- with .Values.deployment.pod.labels }}
{{ tpl (toYaml .) $ | trim | indent 8 }}
        {{- end }}
      {{- with .Values.deployment.pod.annotations }}
      annotations:
{{ tpl (toYaml .) $ | trim | indent 8 }}
      {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            {{- if .Values.redis.enabled }}
            - -redis-addr
            - mulder-redis-master:6379
            {{- end }}
          ports:
            - name: http
              containerPort: 8080
          livenessProbe:
            tcpSocket:
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
{{ toYaml .Values.resources | trim | indent 12 }}
      {{- if .Values.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      {{- end }}
