---
{{- if .Values.ingress.enabled }}
apiVersion: v1
kind: Pod
metadata:
  name: {{ include "mulder.fullname" . }}-ingress-test
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
    - name: {{ .Release.Name }}-ingress-test
      image: busybox
      env:
        - name: HOST
          value: {{ .Values.ingress.host }}
        - name: SCHEME
          value: "{{ if .Values.ingress.tls.enabled }}https{{ else }}http{{ end }}"
      command: ["sh", "-c", "wget --spider --server-response -T 1 ${SCHEME}://${HOST}"]
  restartPolicy: Never
{{- end }}
