---
apiVersion: v1
kind: Pod
metadata:
  name: {{ include "mulder.fullname" . }}-service-test
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
    - name: {{ .Release.Name }}-service-test
      image: busybox
      env:
        - name: SERVICE_NAME
          value: {{ .Release.Name }}
        - name: SERVICE_PORT
          value: {{ .Values.service.port | quote }}
      command:
        - "sh"
        - "-c"
        - "wget --spider --server-response -T 1 \
           http://${SERVICE_NAME}:${SERVICE_PORT}/"
  restartPolicy: Never
