---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mulder.fullname" . }}
  labels:
    helm.sh/chart: {{ include "mulder.chart" . }}
    app.kubernetes.io/name: {{ include "mulder.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- with .Values.service.labels }}
{{ tpl (toYaml .) $ | trim | indent 4 }}
    {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
{{ tpl (toYaml .) $ | trim | indent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
  selector:
    app.kubernetes.io/name: {{ include "mulder.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
